# SPDX-License-Identifier: GPL-2.0

ucie-rcar-host-drv-objs := ucie-rcar.o ucie-rcar-host.o
obj-$(CONFIG_UCIE_RCAR_HOST) += ucie-rcar-host-drv.o
ucie-rcar-ep-drv-objs := ucie-rcar.o ucie-rcar-ep.o
obj-$(CONFIG_UCIE_RCAR_EP) += ucie-rcar-ep-drv.o
