# SPDX-License-Identifier: GPL-2.0 OR MIT

camera_xen_front-objs := xen_camera_front.o \
			 xen_camera_front_evtchnl.o \
			 xen_camera_front_v4l2.o \
			 xen_camera_front_cfg.o

obj-$(CONFIG_MEDIA_XEN_FRONTEND) += camera_xen_front.o
