# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_CDNS_I3C_MASTER)		+= i3c-master-cdns.o
obj-$(CONFIG_DW_I3C_MASTER)		+= dw-i3c-master.o
obj-$(CONFIG_SVC_I3C_MASTER)		+= svc-i3c-master.o
obj-$(CONFIG_MIPI_I3C_HCI)		+= mipi-i3c-hci/
i3c-rcar-objs				+= i3c-rcar-main.o i3c-rcar-target.o
obj-$(CONFIG_I3C_RCAR)			+= i3c-rcar.o
obj-$(CONFIG_I3C_RCAR_MASTER)		+= i3c-rcar-master.o
